highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Joshua Adams's Resume
name: Joshua Adams
email: Joshua.sovanh.adams@gmail.com
email_full: mailto:youremail@me.com
website: github.io/sustain
website_full: https://biomadeira.github.io/sustain
github: n7down
#twitter: twitter
linkedin: https://www.linkedin.com/in/joshua-josh-adams-5573bb18
tel: (614) 353-9628
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
postcode:
city: Draper, UT
country: USA
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
